version: '3'

tasks:
  setup-git:
    desc: Add tuananhlai/prototypes-python as a Git remote for subsequent updates if it hasn't been added already.
    cmd: git remote get-url upstream >/dev/null 2>&1 || git remote add upstream https://github.com/tuananhlai/prototypes-python.git
  update-repo:
    desc: Merge the latest changes from tuananhlai/prototypes-python's main branch into the current branch.
    cmd: git pull upstream main --no-ff --no-edit